version: '3.8'

# Ce fichier est utilisé pour construire les images localement, sans utiliser Docker Hub

services:
  # Image de base commune
  common:
    build:
      context: ./microservices/common
      dockerfile: Dockerfile
    image: localhost/dst-mlops-common:local

  # Microservices métier
  gateway-api:
    build:
      context: ./microservices/gateway_api
      dockerfile: Dockerfile
      args:
        DOCKERHUB_USERNAME: localhost
    image: localhost/dst-mlops-gateway_api:local
    depends_on:
      - common

  prediction-api:
    build:
      context: ./microservices/prediction_api
      dockerfile: Dockerfile
      args:
        DOCKERHUB_USERNAME: localhost
    image: localhost/dst-mlops-prediction_api:local
    depends_on:
      - common

  training-api:
    build:
      context: ./microservices/training_api
      dockerfile: Dockerfile
      args:
        DOCKERHUB_USERNAME: localhost
    image: localhost/dst-mlops-training_api:local
    depends_on:
      - common

  data-api:
    build:
      context: ./microservices/data_api
      dockerfile: Dockerfile
      args:
        DOCKERHUB_USERNAME: localhost
    image: localhost/dst-mlops-data_api:local
    depends_on:
      - common
