name: Docker Build and Push Microservices

on:
  push:
    branches:
      - main  # Déclencher le workflow sur les push vers main
    tags:
      - 'v*'  # Déclencher le workflow sur les tags commençant par 'v'

# Définition des permissions nécessaires
permissions:
  contents: read

jobs:
  build-common:
    name: Build Common Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Common Image
        id: meta-common
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-common
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha,format=short
            latest

      - name: Build and push Common Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservices/common
          file: ./microservices/common/Dockerfile
          push: true
          tags: ${{ steps.meta-common.outputs.tags }}
          labels: ${{ steps.meta-common.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-common:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-common:buildcache,mode=max

  docker-build-push:
    name: Build and Push Microservice Images
    needs: build-common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [data_api, gateway_api, prediction_api, training_api]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha,format=short
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservices/${{ matrix.service }}
          file: ./microservices/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dst-mlops-${{ matrix.service }}:buildcache,mode=max
